[package]
name = "pomelo-import"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
pomelo-core.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
encoding_rs.workspace = true
sha2.workspace = true
anyhow.workspace = true

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
