[package]
name = "pomelo-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
frame-profiling = []
native-gpu = [
    "dep:anyhow",
    "dep:gpui",
    "dep:gpui-apple",
    "dep:gpui-wgpu",
    "dep:gpui-windows",
    "dep:metal",
    "dep:windows",
]

[dependencies]
pomelo-core.workspace = true
thiserror.workspace = true
bytemuck.workspace = true
serde.workspace = true
serde_json.workspace = true
sysinfo = { version = "=0.31.4", default-features = false, features = ["system"] }
image.workspace = true
anyhow = { workspace = true, optional = true }
gpui = { workspace = true, optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
gpui-windows = { workspace = true, optional = true }
windows = { workspace = true, optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
gpui-apple = { workspace = true, optional = true, features = ["runtime_shaders"] }
metal = { workspace = true, optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
gpui-wgpu = { workspace = true, optional = true }

[target.'cfg(target_os = "linux")'.dev-dependencies]
naga.workspace = true
futures.workspace = true

[dev-dependencies]
sha2.workspace = true
pomelo-import.workspace = true
anyhow.workspace = true

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
all = { level = "warn", priority = -1 }
