[package]
name = "pomelo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
pomelo-core.workspace = true
pomelo-import.workspace = true
pomelo-render = { workspace = true, features = ["native-gpu"] }
gpui-kit.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
sys-locale.workspace = true
dirs.workspace = true
tempfile.workspace = true
image.workspace = true
base64.workspace = true
chrono.workspace = true
futures.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
rfd = { version = "=0.17.2", default-features = false, features = ["common-controls-v6"] }

[lints]
workspace = true

[build-dependencies]
embed-resource = "=3.0.11"
resvg = { version = "=0.46.0", default-features = false }
