[package]
name = "pomelo-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
rust-i18n.workspace = true
earcut.workspace = true
libm.workspace = true
icu_collator.workspace = true
icu_locale_core.workspace = true
icu_provider_blob.workspace = true
icu_provider.workspace = true

[dev-dependencies]
serde-saphyr.workspace = true
serde_json.workspace = true
syn.workspace = true

[lints]
workspace = true
