"""Copy the current Web canvas MSDF assets, with provenance, into this workspace."""
import hashlib
import json
from pathlib import Path
import shutil
import sys

ROOT = Path(__file__).resolve().parent.parent


def main():
    web = Path(sys.argv[1]).resolve()
    source = web / 'public/fonts/source-han-sans'
    target = ROOT / 'assets/fonts/source-han-sans'
    target.mkdir(parents=True, exist_ok=True)
    manifest = json.loads((source / 'manifest.json').read_text(encoding='utf-8'))
    names = ['core', *[f'{block:02x}' for block in manifest['blocks']]]
    files = ['manifest.json', 'LICENSE.txt', *[f'{name}.{ext}' for name in names for ext in ['json', 'png']]]
    hashes = {}
    for name in files:
        data = (source / name).read_bytes()
        hashes[name] = hashlib.sha256(data).hexdigest()
        shutil.copyfile(source / name, target / name)
    pages = ['// Generated by scripts/sync-web-msdf.py. Do not edit.\n',
             'pub const PAGES: &[(u16, &[u8], &[u8])] = &[\n',
             '    (0, include_bytes!("core.json"), include_bytes!("core.png")),\n']
    for block in manifest['blocks']:
        pages.append(f'    ({block + 1}, include_bytes!("{block:02x}.json"), include_bytes!("{block:02x}.png")),\n')
    pages.append('];\n')
    (target / 'pages.rs').write_text(''.join(pages), encoding='utf-8')
    for name in ['src/lib/text/msdf-font.ts', 'src/lib/text/board-text-glyph-builder.ts',
                 'src/lib/render/font-metrics.ts', 'src/lib/render/board-label-layout.ts',
                 'src/lib/render/label.wgsl']:
        hashes[name] = hashlib.sha256((web / name).read_bytes()).hexdigest()
    (target / 'provenance.json').write_text(json.dumps({'source': str(web), 'files': hashes}, indent=2) + '\n', encoding='utf-8')
    print(f'MSDF_ASSETS_SYNCED: {len(names)} pages; unchanged JSON/PNG; OFL license included')


if __name__ == '__main__':
    main()
